# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'AgroSmart'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
        - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:          
        - targets: ['container-cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
        - targets: ['container-node-exporter:9100']
        
  - job_name: 'traefik'
    scheme: https
    static_configs:
        - targets: ['flysensorec.com']      
        
  - job_name: 'django'
    scrape_interval: 1m
    static_configs:
        - targets: ['container-django:8000']
